import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("pages/Login.tsx"),
  route("dashboard", "pages/Dashboard.tsx"),
  route("products/create", "pages/CreateProduct.tsx"),
  route("products/edit/:id", "pages/EditProduct.tsx"),
  route("products/all", "pages/AllProducts.tsx"),
  route("products/category", "pages/Category.tsx"),
  route("products/brand", "pages/Brand.tsx"),
  route("products/unit", "pages/Unit.tsx"),
  route("products/count-stock", "pages/CountStock.tsx"),
  route("products/stock-adjustments", "pages/AllStockAdjustments.tsx"),
  route("products/stock-adjustments/create", "pages/CreateStockAdjustment.tsx"),
  route("products/stock-adjustments/edit/:id", "pages/EditStockAdjustment.tsx"),
  route("products/stock-adjustments/view/:id", "pages/StockAdjustmentView.tsx"),
  route("products/stock-movement-history", "pages/StockMovementHistory.tsx"),
  route("sales/create", "pages/CreateSale.tsx"),
  route("sales/all", "pages/AllSales.tsx"),
  route("sales/shipments", "pages/Shipments.tsx"),
  route("sales/edit/:id", "pages/EditSale.tsx"),
  route("purchases/create", "pages/CreatePurchase.tsx"),
  route("purchases/all", "pages/AllPurchases.tsx"),
  route("purchases/edit/:id", "pages/EditPurchase.tsx"),
  route("purchases/view/:id", "pages/PurchaseView.tsx"),
  route("customers", "pages/Customers.tsx"),
  route("accounts", "pages/Accounts.tsx"),
  route("deposits", "pages/Deposits.tsx"),
  route("expenses", "pages/Expenses.tsx"),
  route("transfers", "pages/Transfers.tsx"),
  route("payment-methods", "pages/PaymentMethods.tsx"),
  route("ledger", "pages/Ledger.tsx"),
  route("deposit-categories", "pages/DepositCategories.tsx"),
  route("expense-categories", "pages/ExpenseCategories.tsx"),
  route("taxes", "pages/Taxes.tsx"),
  route("reports", "pages/Reports.tsx"),
  route("settings/people-branches", "pages/PeopleBranchAssignment.tsx"),
  route("franchisee/create", "pages/FranchiseeCreate.tsx"),
] satisfies RouteConfig;
