import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("pages/Login.tsx"),
  route("register", "pages/Register.tsx"),
  route("dashboard", "pages/protected/Dashboard.tsx"),
  route("products/create", "pages/protected/CreateProduct.tsx"),
  route("products/edit/:id", "pages/protected/EditProduct.tsx"),
  route("products/all", "pages/protected/AllProducts.tsx"),
  route("products/category", "pages/protected/Category.tsx"),
  route("products/brand", "pages/protected/Brand.tsx"),
  route("products/unit", "pages/protected/Unit.tsx"),
  route("products/count-stock", "pages/protected/CountStock.tsx"),
  route("products/stock-adjustments", "pages/protected/AllStockAdjustments.tsx"),
  route("products/stock-adjustments/create", "pages/protected/CreateStockAdjustment.tsx"),
  route("products/stock-adjustments/edit/:id", "pages/protected/EditStockAdjustment.tsx"),
  route("products/stock-adjustments/view/:id", "pages/protected/StockAdjustmentView.tsx"),
  route("products/stock-movement-history", "pages/protected/StockMovementHistory.tsx"),
  route("sales/create", "pages/protected/CreateSale.tsx"),
  route("sales/all", "pages/protected/AllSales.tsx"),
  route("sales/shipments", "pages/protected/Shipments.tsx"),
  route("sales/edit/:id", "pages/protected/EditSale.tsx"),
  route("purchases/create", "pages/protected/CreatePurchase.tsx"),
  route("purchases/all", "pages/protected/AllPurchases.tsx"),
  route("purchases/edit/:id", "pages/protected/EditPurchase.tsx"),
  route("purchases/view/:id", "pages/protected/PurchaseView.tsx"),
  route("customers", "pages/protected/Customers.tsx"),
  route("accounts", "pages/protected/Accounts.tsx"),
  route("deposits", "pages/protected/Deposits.tsx"),
  route("expenses", "pages/protected/Expenses.tsx"),
  route("transfers", "pages/protected/Transfers.tsx"),
  route("payment-methods", "pages/protected/PaymentMethods.tsx"),
  route("ledger", "pages/protected/Ledger.tsx"),
  route("deposit-categories", "pages/protected/DepositCategories.tsx"),
  route("expense-categories", "pages/protected/ExpenseCategories.tsx"),
  route("taxes", "pages/protected/Taxes.tsx"),
  route("reports", "pages/protected/Reports.tsx"),
  route("settings/people-branches", "pages/protected/PeopleBranchAssignment.tsx"),
  route("franchisee/create", "pages/protected/FranchiseeCreate.tsx"),
  route("SaleView", "pages/protected/SaleView.tsx"),
  route("not-approved", "pages/NotApproved.tsx"),
  route("admin/users", "pages/protected/AdminUsers.tsx"),
  route("admin/users-enhanced", "pages/protected/AdminUsersEnhanced.tsx"),
  route("rbac-test", "pages/protected/RBACTestPage.tsx"),
  route("security/dashboard", "pages/protected/SecurityDashboard.tsx"),
  route("security/audit-trail", "pages/protected/AuditTrailViewer.tsx"),
  route("security/alerts", "pages/protected/SecurityAlerts.tsx"),
  route("security/user-activity", "pages/protected/UserActivityMonitor.tsx"),
  route("security/compliance", "pages/protected/ComplianceReports.tsx"),
] satisfies RouteConfig;
